#pragma once
#include <string>
#include <vector>
#include <set>
#include <optional>
#include <algorithm>
#include <functional>
#include <iostream>
#define WIN32_LEAN_AND_MEAN
#include <Windows.h>
#include <Psapi.h>
